CREATE TABLE users (
    enabled BOOLEAN,
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    language ENUM('ENGLISH', 'FRENCH', 'BILINGUAL') NOT NULL,
    role ENUM('DOCTOR', 'PATIENT', 'ADMIN') NOT NULL,
    gender ENUM('MALE', 'FEMALE') NOT NULL,
    doctor_gender_preference ENUM('MALE', 'FEMALE', 'NONE'),
    patient_capacity INT,
    has_doctor BOOLEAN,
    doctor_id INT,
    address VARCHAR(255),
    kilometer_range INT,
    ver_emails_sent INT,
    beta_key VARCHAR(255) NOT NULL
);


CREATE TABLE confirmation_token (
    token_id INT AUTO_INCREMENT PRIMARY KEY,
    confirmation_token VARCHAR(255) NOT NULL,
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expiration_date TIMESTAMP NOT NULL,
    user_id BIGINT NOT NULL,
    is_expired BOOLEAN DEFAULT FALSE,
    expiration_in_minutes INT,
    ver_emails_sent INT,
    PRIMARY KEY (token_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);



--CREATE TABLE specializations (
--id INT PRIMARY KEY AUTO_INCREMENT,
--allergy_immunology BOOLEAN DEFAULT FALSE,
--anesthesiology BOOLEAN DEFAULT FALSE,
--dermatology BOOLEAN DEFAULT FALSE,
--diagnostic_radiology BOOLEAN DEFAULT FALSE,
--emergency_medicine BOOLEAN DEFAULT FALSE,
--family_medicine BOOLEAN DEFAULT FALSE,
--internal_medicine BOOLEAN DEFAULT FALSE,
--medical_genetics BOOLEAN DEFAULT FALSE,
--neurology BOOLEAN DEFAULT FALSE,
--nuclear_medicine BOOLEAN DEFAULT FALSE,
--obstetrics_gynaecology BOOLEAN DEFAULT FALSE,
--opthalmology BOOLEAN DEFAULT FALSE,
--pathology BOOLEAN DEFAULT FALSE,
--pediatrics BOOLEAN DEFAULT FALSE,
--physical_medicine_rehabilitation BOOLEAN DEFAULT FALSE,
--preventive_medicine BOOLEAN DEFAULT FALSE,
--psychiatry BOOLEAN DEFAULT FALSE,
--radiation_oncology BOOLEAN DEFAULT FALSE,
--surgery BOOLEAN DEFAULT FALSE,
--urology BOOLEAN DEFAULT FALSE,
--als BOOLEAN DEFAULT FALSE,
--alzheimers_dementias BOOLEAN DEFAULT FALSE,
--arthritis BOOLEAN DEFAULT FALSE,
--asthma BOOLEAN DEFAULT FALSE,
--cancer BOOLEAN DEFAULT FALSE,
--copd BOOLEAN DEFAULT FALSE,
--inflammatory_bowel_disease BOOLEAN DEFAULT FALSE,
--cystic_fibrosis BOOLEAN DEFAULT FALSE,
--alcohol_addiction BOOLEAN DEFAULT FALSE,
--prescription_drug_addiction BOOLEAN DEFAULT FALSE,
--drug_addiction BOOLEAN DEFAULT FALSE,
--heroin_addiction BOOLEAN DEFAULT FALSE,
--opioid_addiction BOOLEAN DEFAULT FALSE,
--mood_disorders BOOLEAN DEFAULT FALSE,
--schizophrenia BOOLEAN DEFAULT FALSE,
--anxiety_disorders BOOLEAN DEFAULT FALSE,
--personality_disorders BOOLEAN DEFAULT FALSE,
--eating_disorders BOOLEAN DEFAULT FALSE,
--problem_gambling BOOLEAN DEFAULT FALSE,
--substance_dependency BOOLEAN DEFAULT FALSE
--);